### ISSUE TITLE
False issues detected by the tool

### ISSUE THREAD

**Issue by Giorgi** [JonDouglas/score#2]
`score EntityFrameworkCore.Exceptions.SqlServer 3.1.4`

Output:

`<description> is too short` - Description from package: 

> Handle database errors easily when working with Entity Framework Core. Catch specific exceptions such as UniqueConstraintException, CannotInsertNullException, MaxLengthExceededException, NumericOverflowException or ReferenceConstraintException instead of generic DbUpdateException

`<iconUrl> is deprecated. Use <icon> instead.`

There is no iconUrl in the package, it uses icon element:

![image](https://user-images.githubusercontent.com/580749/110216024-3a335880-7ec6-11eb-8190-03b5a7bdeae5.png)

Link to the package: [EntityFrameworkCore.Exceptions.SqlServer](https://www.nuget.org/packages/EntityFrameworkCore.Exceptions.SqlServer/)

**Comment by JonDouglas** [comment]
@Giorgi This tool tries to limit a description from 60-180 characters. The actual field will support up to 4000 characters. This is mostly a best practice to help tell a casual reader why they might want to know about your package.

Many packages use the description field as a way to include things that normally go into a README. When that is fully supported, then the description field can be used for more concise descriptions.

![image](https://user-images.githubusercontent.com/1288848/110332717-50d0d100-7fe6-11eb-938a-594b26b4dd94.png)

vs.

![image](https://user-images.githubusercontent.com/1288848/110332752-5d552980-7fe6-11eb-91a8-d8cdc44518d9.png)

As for the icon bug, this is definitely just a double validation issue. I added a quick fix for now. Thanks for the report & contribution!

**Comment by Giorgi** [comment]
Thanks for explaining, that makes sense.
