### ISSUE TITLE
"Owners" tag required but not available when creating nuget directly from SDK csproj 

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [JonDouglas/score#4]
when nuget packages are created from SDK csproj there is no possibility to create "Owners" tag
as described in https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target 

in score tool tag owners is requred
so all nuget packages created by SDK csproj will automaticaly have lower score.

Could you please advise?

**Comment by AdaskoTheBeAsT** [comment]
it seems false alarm - adding "Coyright" tag also generates "Owners"

**Comment by loic-sharma** [comment]
I believe this tool is still a work in progress and not all rules are finalized yet. In this case, the owners field shouldn't be set. See:

* Docs: https://docs.microsoft.com/en-us/nuget/reference/nuspec#owners
* Fix: https://github.com/JonDouglas/score/pull/3

**Comment by JonDouglas** [comment]
Thanks for the feedback! I didn't take this into account for the initial draft. It's now included via #3. Thus closing this!
